### ISSUE TITLE
I'm runnning Ubuntu18.04

### ISSUE THREAD

**Issue by ErrorExorY** [usrbinsam/mini-key-server#10]
`Traceback (most recent call last):
  File "/root/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/root/venv/local/lib/python2.7/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/root/venv/local/lib/python2.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/root/venv/local/lib/python2.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/venv/local/lib/python2.7/site-packages/click/core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/root/venv/local/lib/python2.7/site-packages/click/core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/root/venv/local/lib/python2.7/site-packages/flask/cli.py", line 542, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/root/venv/local/lib/python2.7/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/root/venv/local/lib/python2.7/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/var/www/vhosts/zubarion2.de/crm.zubarion-sharing.de/mini-key-server/keyserver.py", line 3, in <module>
    from keyserv import create_app
  File "/var/www/vhosts/zubarion2.de/crm.zubarion-sharing.de/mini-key-server/keyserv/__init__.py", line 70
    def create_user_command(username: str, password: str):
                                    ^
SyntaxError: invalid syntax
`

This is my output of the error.

**Comment by ErrorExorY** [comment]
Ok, used wrong Py version. 2.7 instead of 3.6, but do a tutorial for setup with plesk😅
