### ISSUE TITLE
from keyserv. Models import DB" without this keyserv

### ISSUE THREAD

**Issue by dreamnyj** [usrbinsam/mini-key-server#6]
Hello, I'm very interested in this project. One problem I found is that there is a "from keyserv. Models import DB" without this keyserv. It's not in the catalog either. I don't know how to deal with it. I would appreciate your guidance.

at auth.py

#=============================
import secrets

import argon2
from flask_login import LoginManager, UserMixin

**from keyserv.models import db**

login_manager = LoginManager()
login_manager.session_protection = "strong"

#=================================

Traceback (most recent call last):
  File "D:\project381\flask02\venv\lib\site-packages\flask\cli.py", line 240, in locate_app
    __import__(module_name)
  File "D:\project381\flask02\__init__.py", line 27, in <module>
    from .auth import login_manager, add_user
  File "D:\project381\flask02\auth.py", line 27, in <module>
    from keyserv.models import db
ModuleNotFoundError: No module named 'keyserv'

**Comment by dreamnyj** [comment]
The problem has been solved. I changed the original directory
